### ISSUE TITLE
cannot add enchant nbt

### ISSUE THREAD

**Issue by xbxymax** [ShaneBeee/Sk-NBeeT#15]
**command /w:
	trigger:
		set {test} to diamond sword with nbt "{ench:[{lvl:5s,id:16s}],display:{Name:""Fire!""}}"
		set player's tool to {test}
		~player's tool = diamond sword with nbt "{display:{Name:""Fire!""}}"**

Skript v2.2-dev37c
This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by ShaneBeee** [comment]
1) Why are you using NBT for that? You can just do 
```vb
give player 1 of diamond sword of sharpness 5 named "Fire!"
```
no need for NBT

2) I tried your exact code:
<img width="966" alt="Screen Shot 2019-10-29 at 12 12 24 AM" src="https://user-images.githubusercontent.com/20008482/67745185-cedb9b80-f9e0-11e9-956d-590970a2e052.png">
As you can see, I can not replicate your issue.

**Comment by xbxymax** [comment]
ok, thank you

**Comment by xbxymax** [comment]
However, I would like you to check this issue, it only happens when skript 2.2-dev37. I don't have this problem when I use skript 2.4, but I can't upgrade skript because of the code

**Comment by ShaneBeee** [comment]
> However, I would like you to check this issue, it only happens when skript 2.2-dev37. I don't have this problem when I use skript 2.4, but I can't upgrade skript because of the code

I'm not really sure what to tell ya then. This plugin isn't really reliable on the version of Skript, but if its not working on an outdated unsupported version of Skript, there isn't really much I can do.

**Comment by xbxymax** [comment]
I noticed that when you were in [2.5.0] '-removed NMS classes/support for 1.9.4, 1.10.2, 1.11.2 and 1.13 as these versions of Minecraft are very rarely used' might have something to do with it

**Comment by ShaneBeee** [comment]
I doubt it since those are just NMS classes that have nothing to do with each other.   When I get home i’ll check again.  It might have something to do with the item type reflection.  Skript changed some parameters for item types in 2.3+ that messed some things up.  I’ll take a look at the classes again and see if it’s something that can be fixed.

**Comment by xbxymax** [comment]
Thank you very much.
I can only use 'skript-dev37c' at the moment.
'add '{ench:[{LVL :999s,id:16s}]}" to tool's NBT' is a valid syntax
But 'Give diamond sword with NBT "{ench:[{LVL :999s,id:16s}]}" to player' does not work.

**Comment by ShaneBeee** [comment]
So I did some digging, and it appears there is an issue with the older versions of Skript:

```java
	public void setItemMeta(final Object meta) {
		if (!itemMetaSupported || !(meta instanceof ItemMeta))
			throw new IllegalStateException("" + meta);
		unsetItemMetaEnchs((ItemMeta) meta); //<----- this line
```
as you can see in Skript's setItemMeta method, there is a line to remove enchantments, this is why the enchants from the NBT are getting removed.

There is nothing I can do to fix this. And since Skript has effects/expressions for setting/adding enchants to an item, I see no need to put effort into attempting to fix this. It serves no purpose using NBT for something Skript can do on its own.
